# Generated by Django 6.0.6 on 2026-06-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_label',
            field=models.CharField(default='Office', help_text='e.g. Home, Office, Branch', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='User preferences for email, whatsapp, etc.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GST / Tax ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('business_customer', 'Business Customer'), ('reseller', 'Reseller'), ('vendor', 'Vendor'), ('sales_executive', 'Sales Executive'), ('administrator', 'Administrator')], default='customer', max_length=30),
        ),
    ]
